### ISSUE TITLE
dosen't implement 'accept' method 

### ISSUE THREAD

**Issue by peymanrahi** [mkobuolys/flutter-design-patterns#57]
https://github.com/mkobuolys/flutter-design-patterns/blob/04514284d1e1a55241e3b3a5bd40533ed5ba6f2f/lib/design_patterns/visitor/file.dart#L7C45-L7C45

Hi , thanks for your amazing and inspiring repo,
I just found that in this File class, you didn't implement the 'accept' method of the iFile interface despite that you have used 'implement' keyword here

**Comment by mkobuolys** [comment]
It's because the `File` class is abstract and used only as a base class. Then, specific file types (`AudioFile`, `ImageFile`, etc.) are forced to implement the `accept` method (e.g. https://github.com/mkobuolys/flutter-design-patterns/blob/04514284d1e1a55241e3b3a5bd40533ed5ba6f2f/lib/design_patterns/visitor/files/audio_file.dart).

**Comment by peymanrahi** [comment]
done
